CLASS zcl_la02_bp_salesorder DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zla02_ce_salesorder.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_la02_bp_salesorder IMPLEMENTATION.
ENDCLASS.
